export const TYPES = {
  GET_DEVICES: 'GET_DEVICES',
  GET_PORTS: 'GET_PORTS',
  GET_STATUS: 'GET_STATUS',
  PUT_STATUS: 'PUT_STATUS',
  GET_ROOMS: 'GET_ROOMS',
  PUT_ROOMS: 'PUT_ROOMS',
  GET_ROOM_INDEX: 'GET_ROOM_INDEX',
  PUT_ROOM_INDEX: 'PUT_ROOM_INDEX',
  SOCKET_STATUS: 'SOCKET_STATUS',
  SOCKET_DEVICES: 'SOCKET_DEVICES',
  PUT_USERS: 'PUT_USERS',
  GET_USERS: 'GET_USERS',
  SIGN_IN: 'SIGN_IN',
  SIGN_OUT: 'SIGN_OUT'
}
